In [26]:
import pandas as pd
from sklearn.cross_validation import train_test_split

### trainReduced.csv has redundant fields removed, and all data are scaled to Z-scores (standard deviates from mean)

In [16]:
df = pd.read_csv("../../data/trainReduced.csv")

In [17]:
df.head()

,Unnamed: 0,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,-1.735031,0.039074,-0.788243,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.427180,-0.202973
1,2,-1.734986,0.039074,0.060752,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.372036,-0.202973
2,3,-1.734963,0.039074,-0.788243,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.273189,-0.202973
3,4,-1.734871,0.039074,0.292296,-0.053388,0.361424,0.138157,-0.038206,-0.042102,-0.013493,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.291397,-0.202973
4,5,-1.734826,0.039074,0.446659,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,0.000412,-0.202973

In [18]:
# Remove column "Unnamed: 0" (artifact of data write in R)
df = df.drop(df.columns[[0]], axis = 1)

In [19]:
df.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,-1.735031,0.039074,-0.788243,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.427180,-0.202973
1,-1.734986,0.039074,0.060752,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.372036,-0.202973
2,-1.734963,0.039074,-0.788243,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.273189,-0.202973
3,-1.734871,0.039074,0.292296,-0.053388,0.361424,0.138157,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.291397,-0.202973
4,-1.734826,0.039074,0.446659,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,0.000412,-0.202973

In [20]:
# Replace IDs with int vals
len(df)

76020

In [24]:
df.ix[:, 0] = range(1, 76021)

In [25]:
df.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,0.039074,-0.788243,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.427180,-0.202973
1,2,0.039074,0.060752,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.372036,-0.202973
2,3,0.039074,-0.788243,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.273189,-0.202973
3,4,0.039074,0.292296,-0.053388,0.361424,0.138157,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,-0.291397,-0.202973
4,5,0.039074,0.446659,-0.053388,-0.213262,-0.218812,-0.038206,-0.042102,-0.013493,-0.015538,...,-0.017407,-0.011979,-0.015597,-0.016314,-0.01565,-0.012576,-0.018817,-0.019847,0.000412,-0.202973

# Split df into test and train for initial model building/testing

In [29]:
# First split out TARGET column, to confrom to sklearn style
y = df.ix[:, 'TARGET']

In [31]:
X = df.drop('TARGET', axis = 1)

In [34]:
(X.columns.values)

array(['ID', 'var3', 'var15', 'imp_ent_var16_ult1',
       'imp_op_var39_comer_ult1', 'imp_op_var39_comer_ult3',
       'imp_op_var40_comer_ult1', 'imp_op_var40_comer_ult3',
       'imp_op_var40_efect_ult1', 'imp_op_var40_efect_ult3',
       'imp_op_var40_ult1', 'imp_op_var41_efect_ult1',
       'imp_op_var41_efect_ult3', 'imp_op_var41_ult1',
       'imp_sal_var16_ult1', 'ind_var1_0', 'ind_var1', 'ind_var5_0',
       'ind_var5', 'ind_var6_0', 'ind_var6', 'ind_var8_0', 'ind_var8',
       'ind_var12_0', 'ind_var12', 'ind_var13_0', 'ind_var13_corto_0',
       'ind_var13_corto', 'ind_var13_largo_0', 'ind_var13_largo',
       'ind_var13_medio_0', 'ind_var13', 'ind_var14_0', 'ind_var14',
       'ind_var17_0', 'ind_var17', 'ind_var18_0', 'ind_var19',
       'ind_var20_0', 'ind_var20', 'ind_var24_0', 'ind_var24',
       'ind_var25_cte', 'ind_var26_0', 'ind_var26_cte', 'ind_var25_0',
       'ind_var30_0', 'ind_var30', 'ind_var31_0', 'ind_var31',
       'ind_var32_cte', 'ind_var33_0', 'ind_var33', 'ind_var34_0',
       'ind_var37_cte', 'ind_var37_0', 'ind_var39_0', 'ind_var40_0',
       'ind_var41_0', 'ind_var44_0', 'ind_var44', 'num_var1_0', 'num_var4',
       'num_var5_0', 'num_var5', 'num_var8_0', 'num_var12_0', 'num_var12',
       'num_var13_0', 'num_var13_corto_0', 'num_var13_corto',
       'num_var13_largo', 'num_var14_0', 'num_var14', 'num_var17_0',
       'num_var17', 'num_var26_0', 'num_var25_0', 'num_op_var40_hace2',
       'num_op_var40_hace3', 'num_op_var40_ult1', 'num_op_var41_hace2',
       'num_op_var41_hace3', 'num_op_var41_ult1', 'num_var31_0',
       'num_var31', 'num_var33_0', 'num_var35', 'num_var37_med_ult2',
       'num_var37_0', 'num_var39_0', 'num_var41_0', 'num_var42',
       'saldo_var1', 'saldo_var5', 'saldo_var6', 'saldo_var8',
       'saldo_var12', 'saldo_var13_corto', 'saldo_var13_largo',
       'saldo_var13_medio', 'saldo_var14', 'saldo_var17', 'saldo_var20',
       'saldo_var26', 'saldo_var25', 'saldo_var31', 'saldo_var33',
       'saldo_var34', 'saldo_var37', 'var36', 'delta_imp_aport_var13_1y3',
       'delta_imp_aport_var17_1y3', 'delta_imp_aport_var33_1y3',
       'delta_imp_compra_var44_1y3', 'delta_imp_reemb_var13_1y3',
       'delta_imp_reemb_var17_1y3', 'delta_imp_reemb_var33_1y3',
       'delta_imp_trasp_var17_in_1y3', 'delta_imp_trasp_var17_out_1y3',
       'delta_imp_trasp_var33_in_1y3', 'delta_imp_trasp_var33_out_1y3',
       'delta_imp_venta_var44_1y3', 'imp_aport_var13_hace3',
       'imp_aport_var13_ult1', 'imp_aport_var17_hace3',
       'imp_aport_var17_ult1', 'imp_aport_var33_hace3',
       'imp_aport_var33_ult1', 'imp_var7_emit_ult1', 'imp_var7_recib_ult1',
       'imp_compra_var44_hace3', 'imp_compra_var44_ult1',
       'imp_reemb_var13_ult1', 'imp_reemb_var17_hace3',
       'imp_reemb_var17_ult1', 'imp_var43_emit_ult1',
       'imp_trans_var37_ult1', 'imp_trasp_var17_in_hace3',
       'imp_trasp_var17_in_ult1', 'imp_trasp_var17_out_ult1',
       'imp_trasp_var33_in_hace3', 'imp_trasp_var33_in_ult1',
       'imp_venta_var44_hace3', 'imp_venta_var44_ult1',
       'ind_var7_emit_ult1', 'ind_var7_recib_ult1', 'ind_var10_ult1',
       'ind_var10cte_ult1', 'ind_var9_cte_ult1', 'ind_var9_ult1',
       'ind_var43_emit_ult1', 'ind_var43_recib_ult1', 'var21',
       'num_aport_var13_hace3', 'num_aport_var13_ult1',
       'num_aport_var17_hace3', 'num_aport_var17_ult1',
       'num_aport_var33_hace3', 'num_aport_var33_ult1',
       'num_var7_recib_ult1', 'num_compra_var44_hace3',
       'num_compra_var44_ult1', 'num_ent_var16_ult1', 'num_var22_hace2',
       'num_var22_hace3', 'num_var22_ult1', 'num_med_var22_ult3',
       'num_med_var45_ult3', 'num_meses_var5_ult3', 'num_meses_var8_ult3',
       'num_meses_var12_ult3', 'num_meses_var13_corto_ult3',
       'num_meses_var13_largo_ult3', 'num_meses_var17_ult3',
       'num_meses_var29_ult3', 'num_meses_var33_ult3',
       'num_meses_var39_vig_ult3', 'num_meses_var44_ult3',
       'num_op_var39_comer_ult1', 'num_op_var39_comer_ult3',
       'num_op_var40_comer_ult1', 'num_op_var40_comer_ult3',
       'num_op_var40_efect_ult1', 'num_op_var40_efect_ult3',
       'num_op_var41_efect_ult1', 'num_op_var41_efect_ult3',
       'num_reemb_var17_ult1', 'num_sal_var16_ult1', 'num_var43_emit_ult1',
       'num_var43_recib_ult1', 'num_trasp_var11_ult1',
       'num_trasp_var17_in_hace3', 'num_trasp_var33_in_hace3',
       'num_venta_var44_hace3', 'num_venta_var44_ult1', 'num_var45_hace2',
       'num_var45_hace3', 'num_var45_ult1', 'saldo_medio_var5_hace2',
       'saldo_medio_var5_hace3', 'saldo_medio_var5_ult1',
       'saldo_medio_var5_ult3', 'saldo_medio_var8_hace2',
       'saldo_medio_var8_hace3', 'saldo_medio_var8_ult1',
       'saldo_medio_var8_ult3', 'saldo_medio_var12_hace2',
       'saldo_medio_var12_hace3', 'saldo_medio_var12_ult1',
       'saldo_medio_var12_ult3', 'saldo_medio_var13_corto_hace2',
       'saldo_medio_var13_corto_hace3', 'saldo_medio_var13_corto_ult1',
       'saldo_medio_var13_corto_ult3', 'saldo_medio_var13_largo_hace2',
       'saldo_medio_var13_largo_hace3', 'saldo_medio_var13_largo_ult1',
       'saldo_medio_var13_largo_ult3', 'saldo_medio_var17_hace2',
       'saldo_medio_var17_hace3', 'saldo_medio_var17_ult1',
       'saldo_medio_var17_ult3', 'saldo_medio_var29_hace2',
       'saldo_medio_var29_hace3', 'saldo_medio_var33_hace2',
       'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1',
       'saldo_medio_var33_ult3', 'saldo_medio_var44_hace2',
       'saldo_medio_var44_hace3', 'saldo_medio_var44_ult1',
       'saldo_medio_var44_ult3', 'var38'], dtype=object)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)